### ISSUE TITLE
Gears Macros are not working in V10

### ISSUE THREAD

**Issue by nschoenwald** [grimmash/tors_tomb_of_the_nine_gods#10]
It seems to me like the gears macros were not adapted for V10. They don't work at all and generate error messages in the console.

**Comment by grimmash** [comment]
The gear macros are provided as is, sadly.  I recommend checking in the ToA DM's Discord for support.  We developed the macros back in early v9.  I will ask if anyone has updated them to be v10 functional, and if so, add the info to the wiki/module.

**Comment by grimmash** [comment]
Looking into it, the fix has two parts:

In the macros change "...document.data.rotation"  to "...document.rotation".

The second part is the Vehicles and Mechanisms mod creator needs to up a PR.  Unsure if this has happened yet.  When I last tlooked at it, the V&H mod was not fully working in v10.

**Comment by grimmash** [comment]
Closing as macros are provided as-is, and this is dependent on another mod.  Sucks, but I can't manage other mods :(
